### ISSUE TITLE
Entry with empty duration fails

### ISSUE THREAD

**Issue by pluskal** [LibreCodeCoop/GitLabBundle#2]
I try to use Kamai in a "toggl" like way - start an entry, and when completed. 

I am getting the following error `Changes could not be saved: No result was found for query although at least one row was expected.
`

I have noticed that this happens only for projects that have GitLab project id assigned. The error occurs with Gitlab issue ID set to existing issue, default 0, and none.

**Comment by Sim0nW0lf** [comment]
I am having the same issue.

Sadly this makes live time tracking impossible and therefore it makes this plugin unusable for our company :/
Also if no issue is selected it doesn't work.

It would be really awesome if that could be fixed. :)

**Comment by Sim0nW0lf** [comment]
Fixing this issue might be pretty easy (just guessing, I have no clue if it is as easy). Just adding an exception when  TimesheetCreatePostEvent is triggered like this:

On TimesheetCreatePostEventf if an IssueID is found & duration is set send a request to GitLab

**Comment by vitormattos** [comment]
Hi @Sim0nW0lf 
Can we close this issue? Solved?

**Comment by Sim0nW0lf** [comment]
Yes, this issue is solved, thank you for your project! :)
